[versions]
kotlin = "2.1.0"
coroutines = "1.9.0"
serialization = "1.7.3"
atomicfu = "0.26.0"
vertx = "4.5.11"
slf4j = "2.0.16"
hikari = "6.2.1"
logback = "1.5.12"
kotlin-wrappers = "1.0.0-pre.830"
kotlin-test = "2.1.0"
testcontainers = "1.20.4"
mockk = "1.13.13"
postgres = "42.7.4"
ksp = "2.1.0-1.0.29"
datetime = "0.6.1"
java-jwt = "4.4.0"
kotlinpoet = "1.18.1"
ksp-api = "2.1.0-1.0.29"
netty = "4.1.115.Final"

[libraries]
# Kotlin Core
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin-test" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-serialization-cbor = { module = "org.jetbrains.kotlinx:kotlinx-serialization-cbor", version.ref = "serialization" }
kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }

# Vert.x (JVM)
vertx-core = { module = "io.vertx:vertx-core", version.ref = "vertx" }
vertx-web = { module = "io.vertx:vertx-web", version.ref = "vertx" }
vertx-kotlin-coroutines = { module = "io.vertx:vertx-lang-kotlin-coroutines", version.ref = "vertx" }
vertx-sql-client = { module = "io.vertx:vertx-sql-client", version.ref = "vertx" }
vertx-pg-client = { module = "io.vertx:vertx-pg-client", version.ref = "vertx" }
vertx-redis-client = { module = "io.vertx:vertx-redis-client", version.ref = "vertx" }

# Database (JVM)
postgres-driver = { module = "org.postgresql:postgresql", version.ref = "postgres" }
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }

# Logging (JVM)
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

# Kotlin Wrappers (Wasm)
kotlin-wrappers-browser = { module = "org.jetbrains.kotlin-wrappers:kotlin-browser", version.ref = "kotlin-wrappers" }
kotlin-wrappers-node = { module = "org.jetbrains.kotlin-wrappers:kotlin-node", version.ref = "kotlin-wrappers" }

# Testing
testcontainers-core = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

# DateTime
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }

# JWT (JVM)
java-jwt = { module = "com.auth0:java-jwt", version.ref = "java-jwt" }

# KSP
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp-api" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoet" }

# Netty
netty-codec-http = { module = "io.netty:netty-codec-http", version.ref = "netty" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-atomicfu = { id = "org.jetbrains.kotlin.plugin.atomicfu", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
